name: Build

on:
  push:
    branches:
    - '**'
    - 'release/**'
    paths-ignore:
    - '.gitignore'
    - 'LICENSE'
    - 'README.md'
  pull_request:
    branches:
    - '**'
    - '!release/**'
    paths-ignore:
    - '.gitignore'
    - 'LICENSE'
    - 'README.md'
  create:
    branches:
    - 'release/**'

env:
  # Use SHA or tag instead of the branch for caching purposes.
  MONO_TAG: rg-mono-unity-2022
  PYTHON_VERSION: '3.11'
  # Should match the version that Mono supports.
  EMSDK_VERSION: 1.39.9
  ANDROID_CMAKE_VERSION: 3.10.2.4988404
  # These should be synced with the Godot repo.
  # platform/android/java/app/config.gradle
  ANDROID_PLATFORM: android-30
  ANDROID_NDK_VERSION: 23.1.7779620
  # platform/iphone/detect.py
  IOS_VERSION_MIN: 10.0

jobs:
  llvm:
    name: LLVM
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        target: [llvm64, llvmwin64]
        exclude:
          # We already build for Windows on ubuntu-latest
          - os: macos-latest
            target: llvmwin64
    steps:
      - name: Cache LLVM
        id: cache_llvm
        uses: actions/cache@v3
        with:
          path: ~/mono-installs/llvm-${{ matrix.target }}
          key: ${{ runner.os }}-${{ env.MONO_TAG }}-llvm-${{ matrix.target }}
      - name: Set Environment Variables
        run: |
          echo "MONO_SOURCE_ROOT=$GITHUB_WORKSPACE/mono_sources" >> $GITHUB_ENV
      - name: Install Dependencies (Linux)
        if: steps.cache_llvm.outputs.cache-hit != 'true' && runner.os == 'Linux'
        run: |
          sudo apt-get -y update
          sudo apt-get -y install git autoconf libtool libtool-bin automake gettext cmake=3.5 python3 curl
      - name: Install Linux SDK (x86_64)
        if: steps.cache_llvm.outputs.cache-hit != 'true' && runner.os == 'Linux'
        run: |
          cd /home/runner
          curl -LO https://downloads.tuxfamily.org/godotengine/toolchains/linux/2021-02-11/x86_64-godot-linux-gnu_sdk-buildroot.tar.bz2 -k
          tar xf x86_64-godot-linux-gnu_sdk-buildroot.tar.bz2
          rm -f x86_64-godot-linux-gnu_sdk-buildroot.tar.bz2
          cd x86_64-godot-linux-gnu_sdk-buildroot
          ./relocate-sdk.sh
          cd bin
          rm -f {aclocal*,auto*,libtool*,m4}
          for file in x86_64-godot-*; do alias=$(echo $file | sed "s/godot-//"); ln -s $file $alias; done
          echo "PATH=/home/runner/x86_64-godot-linux-gnu_sdk-buildroot/bin:${PATH}" >> $GITHUB_ENV
      - name: Install Dependencies (Linux Targeting Windows)
        if: steps.cache_llvm.outputs.cache-hit != 'true' && runner.os == 'Linux' && matrix.target == 'llvmwin64'
        run: |
          sudo apt-get -y install mingw-w64 libz-mingw-w64-dev
      - name: Install Dependencies (macOS)
        if: steps.cache_llvm.outputs.cache-hit != 'true' && matrix.os == 'macos-latest'
        run: |
          brew install autoconf 
          brew install automake 
          brew install libtool
          brew extract — version=3.28.1 cmake homebrew/cask 
          brew install cmake@3.28.1
      - name: Cache Mono Sources
        if: steps.cache_llvm.outputs.cache-hit != 'true'
        id: cache_mono_sources
        uses: actions/cache@v3
        with:
          path: ${{ env.MONO_SOURCE_ROOT }}
          key: ${{ runner.os }}-${{ env.MONO_TAG }}-mono-sources
      - name: Checkout Mono Sources
        if: steps.cache_mono_sources.outputs.cache-hit != 'true' && steps.cache_llvm.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: dj4156003/mono
          ref: ${{ env.MONO_TAG }}
          submodules: true
          path: ${{ env.MONO_SOURCE_ROOT }}
      - name: Clean Mono
        if: steps.cache_llvm.outputs.cache-hit != 'true'
        run: pushd ${{ env.MONO_SOURCE_ROOT }} && git reset --hard && git clean -xffd && git submodule foreach --recursive git reset --hard && git submodule foreach --recursive git clean -xffd && git submodule update --init --recursive && popd
      - name: Checkout
        if: steps.cache_llvm.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          path: godot-mono-builds
      - name: Setup Python
        if: steps.cache_llvm.outputs.cache-hit != 'true'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Patch Mono
        if: steps.cache_llvm.outputs.cache-hit != 'true'
        run:
          python3 godot-mono-builds/patch_mono.py
      - name: Make
        if: steps.cache_llvm.outputs.cache-hit != 'true'
        run:
          python3 godot-mono-builds/llvm.py make --target=${{ matrix.target }} -j 2
      - name: Upload LLVM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: llvm-${{ matrix.target }}-${{ matrix.os }}
          path: ~/mono-installs/llvm-${{ matrix.target }}
      - name: Clean Mono
        if: steps.cache_llvm.outputs.cache-hit != 'true'
        run: pushd ${{ env.MONO_SOURCE_ROOT }} && git reset --hard && git clean -xffd && git submodule foreach --recursive git reset --hard && git submodule foreach --recursive git clean -xffd && git submodule update --init --recursive && popd
      - name: Upload config.log After Error
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: llvm-${{ matrix.target }}-${{ matrix.os }}-config.log
          path: ~/mono-configs/llvm-${{ matrix.target }}/config.log
